spring:
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/clients/**
        - id: config-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/configurations/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/notifications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

  application:
    name: api-gateway

server:
  port: 8080
